// =============================================================================
// PORTFOLIO — central config for the Wisnotech AI video studio page (/portfolio).
//
// This is the SINGLE place to add new pieces of work. Copy an entry below, point
// `src`/`poster` at a file in public/ and it appears on the page automatically —
// filters, lightbox and all.
//
// NEW UPLOADS: drop new video files in `public/portfolio/videos/` and let the
// build tooling generate thumbnails into `public/portfolio/thumbs/`. Existing
// entries below may still point at shared `/wino/...` media from the WINO page —
// they are read-only and should stay as-is.
// =============================================================================

export interface PortfolioCategory {
  id: string;
  label: string;
  /** Accent color used across chips, badges and the lightbox. */
  accent: string;
}

export interface PortfolioSample {
  id: string;
  type: "video" | "image";
  title: string;
  description: string;
  /** The generation prompt that created this piece (revealed on hover / in the lightbox). */
  prompt: string;
  category: PortfolioCategory["id"];
  src: string;
  poster?: string;
  /** Intrinsic media size (px) — cards keep the real aspect ratio. */
  width: number;
  height: number;
  /** Clip length in seconds (videos only). Renders a duration badge. */
  durationSeconds?: number;
  tags: string[];
  /** Featured samples get a badge and show first in the grid. */
  featured?: boolean;
  /** `false` hides the sample from the public page. */
  published: boolean;
}

export const PORTFOLIO_CATEGORIES: PortfolioCategory[] = [
  { id: "cinematic", label: "Cinematic", accent: "#7aa5ff" },
  { id: "character", label: "Character", accent: "#ff7a9e" },
  { id: "text-to-video", label: "Text-to-Video", accent: "#3b7bff" },
  { id: "image-to-video", label: "Image-to-Video", accent: "#8b7aff" },
  { id: "social-media", label: "Social Content", accent: "#2dd4bf" },
  { id: "advertising", label: "Ads & UGC", accent: "#fbbf24" },
  { id: "ai-image", label: "Campaign Stills", accent: "#a78bfa" },
  { id: "film", label: "Film & Trailers", accent: "#f472b6" },
];

export const PORTFOLIO_SAMPLES: PortfolioSample[] = [
  {
    id: "p1",
    type: "video",
    title: "The City at Golden Hour",
    description: "A hand-held text-to-video street scene in warm dusk light — atmosphere that makes any brand feel alive.",
    category: "text-to-video",
    prompt: "Handheld 35mm footage of a bustling Lagos street market at golden hour. Warm amber sunlight cuts through dust and smoke, catching the faces of vendors and commuters moving in rhythm. Shallow depth of field, slight lens breathing, filmic amber-to-teal grade, visible grain in the shadows, the camera drifting naturally with the crowd and catching authentic candid moments. Vertical 9:16 framing.",
    src: "/wino/videos/showreel-1.mp4",
    poster: "/wino/thumbs/video-thumb-1.jpg",
    width: 480,
    height: 852,
    durationSeconds: 15,
    tags: ["street", "golden hour", "9:16"],
    featured: true,
    published: true,
  },
  {
    id: "p2",
    type: "video",
    title: "Drop Day",
    description: "A 15-second launch film built from a single prompt — the energy of a product drop, minus the shoot day.",
    category: "advertising",
    prompt: "High-energy 15-second product launch advertisement. A sleek sneaker floating and rotating in a dark studio, lit by dramatic rim light and sweeping neon accents in blue and magenta. Fast punchy cuts between macro close-ups of texture, laces and sole, dust particles catching the light, subtle camera shake on the beat. Glossy reflections, lens flares, bold contrast, cinematic product cinematography, final frame holding on the product with the brand accent glowing.",
    src: "/wino/videos/showreel-2.mp4",
    poster: "/wino/thumbs/video-thumb-2.jpg",
    width: 720,
    height: 1280,
    durationSeconds: 15,
    tags: ["ad", "product", "9:16"],
    featured: true,
    published: true,
  },
  {
    id: "p3",
    type: "video",
    title: "Portrait, Alive",
    description: "One still portrait, given life — an image-to-video push that turns a frame into a scene.",
    category: "image-to-video",
    prompt: "A slow cinematic push-in on a studio portrait of a young woman. The still image subtly comes to life, hair moving a fraction, eyes catching the light, breath hinted in the chest. Soft key light from the left, gentle fill, deep black background, shallow depth of field. The camera pushes forward with a barely perceptible dolly until the frame feels like a living photograph.",
    src: "/wino/videos/showreel-3.mp4",
    poster: "/wino/thumbs/video-thumb-3.jpg",
    width: 720,
    height: 1280,
    durationSeconds: 15,
    tags: ["portrait", "camera move", "9:16"],
    featured: true,
    published: true,
  },
  {
    id: "p4",
    type: "video",
    title: "The Character Lives",
    description: "A character with one face and endless emotion — consistent, expressive and ready for its close-up.",
    category: "character",
    prompt: "A single consistent character across a sequence of emotions, the same face, same wardrobe, same world. Close-up and medium shots of a weathered man in a brown coat shifting from calm to grief to quiet resolve. Natural skin texture, expressive micro-expressions, motion blur on subtle head turns, warm filmic grade with soft window light. The character reads as one person across every cut.",
    src: "/wino/videos/showreel-4.mp4",
    poster: "/wino/thumbs/video-thumb-4.jpg",
    width: 720,
    height: 1280,
    durationSeconds: 8,
    tags: ["character", "motion", "9:16"],
    published: true,
  },
  {
    id: "p5",
    type: "video",
    title: "Made for the Feed",
    description: "A vertical social clip engineered to stop the scroll — punchy, on-brand and repeatable.",
    category: "social-media",
    prompt: "Vertical 9:16 lifestyle loop of a young woman in modern athleisure walking through a sunlit city plaza and pausing to adjust her sunglasses. On-brand palette of warm neutrals and teal accents, smooth slow-motion camera orbit, autumnal light, soft shadows, natural fabric movement, looped cleanly with no visible seam. Scroll-stopping energy with a premium editorial tone.",
    src: "/wino/videos/showreel-5.mp4",
    poster: "/wino/thumbs/video-thumb-5.jpg",
    width: 720,
    height: 1280,
    durationSeconds: 15,
    tags: ["social", "9:16"],
    published: true,
  },
  {
    id: "p6",
    type: "image",
    title: "Neon Market at Midnight",
    description: "A campaign still with the gravity of a film still — neon, night and a world of product placements waiting.",
    category: "ai-image",
    prompt: "A cinematic still of a neon-soaked night market at midnight. Wet asphalt reflects magenta and cyan signage, steam rises from food stalls, silhouettes of vendors and customers move through layered depths, haze softens distant lights into bokeh. Moody atmospheric depth, high dynamic range, filmic grade with crushed blacks, vertical 9:16 composition.",
    src: "/wino/images/1.jpeg",
    width: 1536,
    height: 2752,
    tags: ["neon", "night", "still"],
    published: true,
  },
  {
    id: "p7",
    type: "image",
    title: "Face in Studio Light",
    description: "A dramatic studio portrait — the kind of imagery that anchors a campaign identity.",
    category: "ai-image",
    prompt: "A dramatic studio portrait of a man with a strong jawline, lit in classic Rembrandt style, a triangle of light under the left eye and deep shadow on the right side. Dark charcoal background, fine skin texture and pores visible, confident direct gaze into camera, subtle catchlights in the eyes, editorial campaign quality, vertical 9:16 crop.",
    src: "/wino/images/2.jpeg",
    width: 1536,
    height: 2752,
    tags: ["portrait", "studio", "still"],
    published: true,
  },
  {
    id: "p8",
    type: "image",
    title: "The Long Horizon",
    description: "An expansive cinematic landscape — our stills carry the same scale as our motion.",
    category: "ai-image",
    prompt: "An expansive cinematic landscape of layered mountain ridges at golden hour. A lone figure stands on a ridge in the middle distance for scale, warm light rakes across the peaks, mist sits in the valleys, the sky fades from amber to cool blue. Epic scale, atmospheric perspective, filmic color grade, strong leading lines across the horizon.",
    src: "/wino/images/3.jpeg",
    width: 1536,
    height: 2752,
    tags: ["landscape", "cinematic", "still"],
    published: true,
  },
  {
    id: "p9",
    type: "video",
    title: "First Frames of a Film",
    description: "A narrative teaser with filmic grading and deliberate pacing — a story in 44 seconds.",
    category: "film",
    prompt: "Opening sequence of a moody mystery film. Rain-slicked city streets at night, neon reflections smearing across the asphalt, a silhouette standing under a streetlight. Slow dolly pushes, deliberate pacing, shallow focus, heavy filmic grade with green-teal shadows and warm highlights, grain and subtle flicker. Building suspense through restraint, 44 seconds of atmosphere before the reveal.",
    src: "/wino/videos/showreel-6.mp4",
    poster: "/wino/thumbs/video-thumb-6.jpg",
    width: 720,
    height: 1280,
    durationSeconds: 44,
    tags: ["film", "teaser", "9:16"],
    published: true,
  },
  {
    id: "p10",
    type: "video",
    title: "City Pulse 01",
    description: "A vertical slice of street life crafted to hold attention in a scrolling feed.",
    category: "social-media",
    prompt: "Vertical 9:16 street-life vignette in warm daylight. Candid moments of commuters crossing a busy intersection, market stalls, a cyclist weaving through traffic. Handheld and energetic, natural motion and authentic reactions, golden sunlight flaring between buildings, warm filmic grade. The energy of a city moving in rhythm.",
    src: "/wino/videos/vertical-01.mp4",
    poster: "/wino/thumbs/vertical-01.jpg",
    width: 406,
    height: 720,
    durationSeconds: 8,
    tags: ["street", "9:16"],
    published: true,
  },
  {
    id: "p11",
    type: "video",
    title: "City Pulse 02",
    description: "Another street, another mood — consistent energy for brand-led social content.",
    category: "social-media",
    prompt: "Vertical 9:16 street vignette at evening. Cool blue-hour tones, office lights flickering on, a lone figure walking against the flow of traffic, reflections on wet pavement, the low hum of the city. Slower, contemplative pacing, shallow depth of field, filmic teal-heavy grade, cinematic street energy.",
    src: "/wino/videos/vertical-02.mp4",
    poster: "/wino/thumbs/vertical-02.jpg",
    width: 406,
    height: 720,
    durationSeconds: 8,
    tags: ["street", "9:16"],
    published: true,
  },
  {
    id: "p12",
    type: "video",
    title: "City Pulse 03",
    description: "The third beat in a series — proof a campaign can live on repeat without going stale.",
    category: "social-media",
    prompt: "Vertical 9:16 night-street series beat. Neon signs and shopfronts glow in magenta and cyan, a crowd moves through the frame in motion blur, headlights streak past, steam rises from a food cart. Dynamic framing, high contrast, cinematic grade with crushed shadows, the energy of a city that never sleeps.",
    src: "/wino/videos/vertical-03.mp4",
    poster: "/wino/thumbs/vertical-03.jpg",
    width: 406,
    height: 720,
    durationSeconds: 8,
    tags: ["street", "9:16"],
    published: true,
  },
  {
    id: "p13",
    type: "video",
    title: "Portrait in Motion",
    description: "A shallow-depth portrait that moves — cinematic depth for premium brand moments.",
    category: "cinematic",
    prompt: "Vertical 9:16 cinematic portrait of a woman by a rain-streaked window. Shallow depth of field with creamy bokeh from city lights behind her, gentle camera drift from waist to face, soft window light sculpting her features, fine film grain, muted filmic grade. Premium editorial mood, quiet and intimate.",
    src: "/wino/videos/portrait-moment.mp4",
    poster: "/wino/thumbs/portrait-moment.jpg",
    width: 720,
    height: 1280,
    durationSeconds: 8,
    tags: ["portrait", "bokeh", "9:16"],
    published: true,
  },
  {
    id: "p14",
    type: "video",
    title: "A Film Still, Breathing",
    description: "A composed 16:9 shot with a filmic grade — the quiet power of a locked-off scene.",
    category: "cinematic",
    prompt: "A locked-off 16:9 narrative shot. A man sits at a table in a dim study, lit by a single lamp, dust floating in the beam, bookshelves receding into shadow. Composed blocking, symmetrical framing, restrained movement, filmic grade with deep shadows, the quiet power of a scene that holds its breath.",
    src: "/wino/videos/cinematic-01.mp4",
    poster: "/wino/thumbs/cinematic-01.jpg",
    width: 1280,
    height: 720,
    durationSeconds: 8,
    tags: ["16:9", "narrative", "filmic"],
    published: true,
  },
  {
    id: "p15",
    type: "video",
    title: "The Long Take",
    description: "Subtle camera drift across a cinematic frame — motion that never distracts from the story.",
    category: "cinematic",
    prompt: "A single 16:9 long take with subtle camera drift. A couple walks along a windswept coastal path at dusk, the camera tracking beside them with a barely perceptible push, clouds moving fast overhead, the sea shimmering in low light. Naturalistic light, desaturated filmic grade, restrained cinematic motion that never distracts from the story.",
    src: "/wino/videos/cinematic-02.mp4",
    poster: "/wino/thumbs/cinematic-02.jpg",
    width: 1280,
    height: 720,
    durationSeconds: 8,
    tags: ["16:9", "narrative", "filmic"],
    published: true,
  },
  {
    id: "p16",
    type: "video",
    title: "Six Stories, One Frame",
    description: "A wide montage of multiple AI generations — the scale of what one workflow can produce.",
    category: "cinematic",
    prompt: "A wide 16:9 montage grid of six AI-generated scenes in one frame, a desert, a city street, a forest, a warehouse, a portrait and a coastline, each in a different cinematic grade but unified by a shared palette and texture. The mosaic reads as a single storyboard for a feature film, crossfading between tiles over 15 seconds.",
    src: "/wino/videos/showcase-matrix.mp4",
    poster: "/wino/thumbs/showcase-matrix.jpg",
    width: 1280,
    height: 720,
    durationSeconds: 15,
    tags: ["montage", "16:9", "multi-scene"],
    featured: true,
    published: true,
  },
  {
    id: "p17",
    type: "video",
    title: "The Wide Frame",
    description: "An ultrawide text-to-video generation — cinematic scope from a single line of direction.",
    category: "text-to-video",
    prompt: "Ultrawide anamorphic text-to-video scene. A vast savanna at dawn with a herd moving across the frame, cinematic light raking through dust, distant mountains under a gradient sky. Epic landscape, scope and silence, anamorphic lens flares, filmic grade, the wide frame making everything feel larger than life.",
    src: "/wino/videos/seedance-demo.mp4",
    poster: "/wino/thumbs/seedance-demo.jpg",
    width: 1280,
    height: 548,
    durationSeconds: 8,
    tags: ["text-to-video", "wide", "demo"],
    published: true,
  },
  {
    id: "p18",
    type: "video",
    title: "Unbroken",
    description: "A 26-second vertical action sequence — fast cuts, real momentum, zero stunt budget.",
    category: "character",
    prompt: "26-second vertical 9:16 action sequence in a rain-soaked corridor at night. A lone fighter in a dark suit takes on three opponents with precise, brutal choreography, fast cuts, whip pans, slow-motion impacts, sparks and droplets frozen in the light. Practical energy, stunt-free momentum, neon-cyan accents, filmic grade with crushed blacks, unbroken rhythm from the first hit to the final stance.",
    src: "/wino/videos/johnwick-character.mp4",
    poster: "/wino/thumbs/johnwick-character.jpg",
    width: 1080,
    height: 1920,
    durationSeconds: 26,
    tags: ["action", "character", "9:16"],
    featured: true,
    published: true,
  },
  {
    id: "p19",
    type: "video",
    title: "The Workshop Assassin",
    description: "A gritty character vignette in a working workshop — mood, texture and menace on demand.",
    category: "character",
    prompt: "Gritty 16:9 character vignette set in a working workshop at night. A masked figure in tactical gear assembles a blade at a steel table, sparks from a grinder flaring in the dark, oil and dust in the air, chain-link shadow patterns on the wall. Cinematic menace, Rembrandt-style rim lighting, filmic grade, slow deliberate moves.",
    src: "/wino/videos/factory-ninja.mp4",
    poster: "/wino/thumbs/factory-ninja.jpg",
    width: 1280,
    height: 720,
    durationSeconds: 15,
    tags: ["character", "16:9", "workshop"],
    published: true,
  },
  {
    id: "p20",
    type: "video",
    title: "A Desert Epic",
    description: "An epic-scale trailer sequence from a single prompt — proof that ‘big film’ no longer needs a big budget.",
    category: "film",
    prompt: "Epic-scale sci-fi desert trailer sequence. A lone figure in flowing robes climbs a colossal dune under twin suns, swirling sand storms across the frame, a distant city-temple on the horizon, giant shadows of machines moving below the ridge. Orchestral tension, anamorphic scope, burnt-orange and teal grade, 16:9. Big film with no big budget.",
    src: "/portfolio/videos/dune-trailer.mp4",
    poster: "/portfolio/thumbs/dune-trailer.jpg",
    width: 1280,
    height: 720,
    durationSeconds: 13,
    tags: ["sci-fi", "trailer", "16:9"],
    featured: true,
    published: true,
  },
  {
    id: "p21",
    type: "video",
    title: "Day One Energy",
    description: "A 30-second fitness vlog with punchy cuts — creator energy, produced to spec.",
    category: "social-media",
    prompt: "30-second fitness vlog with punchy cuts. A creator training in a gritty gym at dawn, heavy bag, skipping rope, deadlifts, intercut with close-ups of chalk, sweat and determined eyes. Motivational energy, handheld camera movement, warm practical lighting, energetic music-driven pacing, creator style with raw authenticity.",
    src: "/portfolio/videos/fitness-vlog.mp4",
    poster: "/portfolio/thumbs/fitness-vlog.jpg",
    width: 1280,
    height: 720,
    durationSeconds: 30,
    tags: ["fitness", "vlog", "16:9"],
    published: true,
  },
  {
    id: "p22",
    type: "video",
    title: "Scroll-Stop 01",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical 9:16 social clip of a woman laughing at a rooftop sunset party, friends blurred in the background, warm golden light, candid handheld energy, subtle slow-motion, a scroll-stopping moment of joy.",
    src: "/portfolio/videos/vertical-a1.mp4",
    poster: "/portfolio/thumbs/vertical-a1.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p23",
    type: "video",
    title: "Scroll-Stop 02",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical 9:16 social clip of a barista pouring latte art in a sunlit coffee shop, steam rising, macro close-ups of the pour, cozy warm tones, a gentle camera push, cleanly looped.",
    src: "/portfolio/videos/vertical-a2.mp4",
    poster: "/portfolio/thumbs/vertical-a2.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p24",
    type: "video",
    title: "Scroll-Stop 03",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical 9:16 social clip of night driving through neon streets, windshield reflections, a soft dashboard glow, moody tones, smooth gimbal motion through the city.",
    src: "/portfolio/videos/vertical-a3.mp4",
    poster: "/portfolio/thumbs/vertical-a3.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p25",
    type: "video",
    title: "Scroll-Stop 04",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical 9:16 social clip of an artist painting on a canvas in a loft studio, paint strokes in close-up, natural window light, a calm and focused mood, filmic grade.",
    src: "/portfolio/videos/vertical-a4.mp4",
    poster: "/portfolio/thumbs/vertical-a4.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p26",
    type: "video",
    title: "Scroll-Stop 05",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical 9:16 social clip of a street dancer popping in an alley at golden hour, spectators as silhouettes, energetic moves, dust in the air, punchy cuts.",
    src: "/portfolio/videos/vertical-a5.mp4",
    poster: "/portfolio/thumbs/vertical-a5.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p27",
    type: "video",
    title: "Scroll-Stop 06",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical 9:16 social clip of a surfer walking toward the ocean at dawn, waves rolling in, backlit spray, a contemplative pace, desaturated dawn grade.",
    src: "/portfolio/videos/vertical-a6.mp4",
    poster: "/portfolio/thumbs/vertical-a6.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p28",
    type: "video",
    title: "Scroll-Stop 07",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical 9:16 social clip of a chef plating a dish in a moody kitchen, steam and fresh herbs, top-down and 45-degree angles, warm cinematic light, precise cuts.",
    src: "/portfolio/videos/vertical-a7.mp4",
    poster: "/portfolio/thumbs/vertical-a7.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 10,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p29",
    type: "video",
    title: "Scroll-Stop 08",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical 9:16 social clip of friends at a neon-lit arcade, playful energy, bokeh lights, laughter, fast cuts and slow-motion beats, vibrant color grade.",
    src: "/portfolio/videos/vertical-a8.mp4",
    poster: "/portfolio/thumbs/vertical-a8.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p30",
    type: "video",
    title: "Scroll-Stop 09",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical 9:16 social clip of rain on a city bus window with blurred night lights outside, a quiet reflective mood, shallow depth, cinematic grade.",
    src: "/portfolio/videos/vertical-a9.mp4",
    poster: "/portfolio/thumbs/vertical-a9.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p31",
    type: "video",
    title: "Cinema Without Cameras",
    description: "A cinematic 16:9 generation from a single prompt — the new economics of filmmaking.",
    category: "cinematic",
    prompt: "Cinematic 16:9 generation from a single prompt. A luxurious penthouse interior at dusk, floor-to-ceiling windows over a glittering skyline, a slow camera push through the space, light playing across marble and glass, anamorphic look, filmic grade, no camera required.",
    src: "/portfolio/videos/web-demo.mp4",
    poster: "/portfolio/thumbs/web-demo.jpg",
    width: 1280,
    height: 720,
    durationSeconds: 13,
    tags: ["16:9", "cinematic"],
    published: true,
  },
];

/** Published samples, featured first, then original order. */
export function loadPortfolioSamples(): PortfolioSample[] {
  return PORTFOLIO_SAMPLES.filter((s) => s.published).sort(
    (a, b) => Number(b.featured ?? false) - Number(a.featured ?? false)
  );
}

export function categoryById(id: string): PortfolioCategory | undefined {
  return PORTFOLIO_CATEGORIES.find((c) => c.id === id);
}

/** "0:08" / "1:02" style clip length. */
export function formatDuration(seconds?: number): string {
  if (!seconds || seconds <= 0) return "";
  const m = Math.floor(seconds / 60);
  const s = Math.round(seconds % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}

/** Best-effort aspect label like "9:16", "16:9" or "Portrait". */
export function aspectLabel(width: number, height: number): string {
  const ratio = width / height;
  if (Math.abs(ratio - 9 / 16) < 0.02) return "9:16";
  if (Math.abs(ratio - 16 / 9) < 0.02) return "16:9";
  if (Math.abs(ratio - 1) < 0.02) return "1:1";
  return height > width ? "Portrait" : "Landscape";
}