// =============================================================================
// PORTFOLIO — central config for the Wisnotech AI video studio page (/portfolio).
//
// This is the SINGLE place to add new pieces of work. Copy an entry below, point
// `src`/`poster` at a file in public/ and it appears on the page automatically —
// filters, lightbox and all.
//
// NEW UPLOADS: drop new video files in `public/portfolio/videos/` and let the
// build tooling generate thumbnails into `public/portfolio/thumbs/`. Existing
// entries below may still point at shared `/wino/...` media from the WINO page —
// they are read-only and should stay as-is.
// =============================================================================

export interface PortfolioCategory {
  id: string;
  label: string;
  /** Accent color used across chips, badges and the lightbox. */
  accent: string;
}

export interface PortfolioSample {
  id: string;
  type: "video" | "image";
  title: string;
  description: string;
  /** The generation prompt that created this piece (revealed on hover / in the lightbox). */
  prompt: string;
  category: PortfolioCategory["id"];
  src: string;
  poster?: string;
  /** Intrinsic media size (px) — cards keep the real aspect ratio. */
  width: number;
  height: number;
  /** Clip length in seconds (videos only). Renders a duration badge. */
  durationSeconds?: number;
  tags: string[];
  /** Featured samples get a badge and show first in the grid. */
  featured?: boolean;
  /** `false` hides the sample from the public page. */
  published: boolean;
}

export const PORTFOLIO_CATEGORIES: PortfolioCategory[] = [
  { id: "cinematic", label: "Cinematic", accent: "#7aa5ff" },
  { id: "character", label: "Character", accent: "#ff7a9e" },
  { id: "text-to-video", label: "Text-to-Video", accent: "#3b7bff" },
  { id: "image-to-video", label: "Image-to-Video", accent: "#8b7aff" },
  { id: "social-media", label: "Social Content", accent: "#2dd4bf" },
  { id: "advertising", label: "Ads & UGC", accent: "#fbbf24" },
  { id: "ai-image", label: "Campaign Stills", accent: "#a78bfa" },
  { id: "film", label: "Film & Trailers", accent: "#f472b6" },
];

export const PORTFOLIO_SAMPLES: PortfolioSample[] = [
  {
    id: "p1",
    type: "video",
    title: "The City at Golden Hour",
    description: "A hand-held text-to-video street scene in warm dusk light — atmosphere that makes any brand feel alive.",
    category: "text-to-video",
    prompt: "Handheld street footage in a Lagos market at golden hour, warm dusk light, dust in the air, people moving in rhythm, 35mm film look",
    src: "/wino/videos/showreel-1.mp4",
    poster: "/wino/thumbs/video-thumb-1.jpg",
    width: 480,
    height: 852,
    durationSeconds: 15,
    tags: ["street", "golden hour", "9:16"],
    featured: true,
    published: true,
  },
  {
    id: "p2",
    type: "video",
    title: "Drop Day",
    description: "A 15-second launch film built from a single prompt — the energy of a product drop, minus the shoot day.",
    category: "advertising",
    prompt: "High-energy 15-second product launch ad, sleek product rotating in dramatic studio light, lens flares, punchy cuts, cinematic product cinematography",
    src: "/wino/videos/showreel-2.mp4",
    poster: "/wino/thumbs/video-thumb-2.jpg",
    width: 720,
    height: 1280,
    durationSeconds: 15,
    tags: ["ad", "product", "9:16"],
    featured: true,
    published: true,
  },
  {
    id: "p3",
    type: "video",
    title: "Portrait, Alive",
    description: "One still portrait, given life — an image-to-video push that turns a frame into a scene.",
    category: "image-to-video",
    prompt: "Slow cinematic push-in on a studio portrait, subtle facial micro-movement, shallow depth of field, soft key light, a film still coming to life",
    src: "/wino/videos/showreel-3.mp4",
    poster: "/wino/thumbs/video-thumb-3.jpg",
    width: 720,
    height: 1280,
    durationSeconds: 15,
    tags: ["portrait", "camera move", "9:16"],
    featured: true,
    published: true,
  },
  {
    id: "p4",
    type: "video",
    title: "The Character Lives",
    description: "A character with one face and endless emotion — consistent, expressive and ready for its close-up.",
    category: "character",
    prompt: "A single consistent character across emotions, expressive face, natural motion, cinematic character study, warm filmic grade",
    src: "/wino/videos/showreel-4.mp4",
    poster: "/wino/thumbs/video-thumb-4.jpg",
    width: 720,
    height: 1280,
    durationSeconds: 8,
    tags: ["character", "motion", "9:16"],
    published: true,
  },
  {
    id: "p5",
    type: "video",
    title: "Made for the Feed",
    description: "A vertical social clip engineered to stop the scroll — punchy, on-brand and repeatable.",
    category: "social-media",
    prompt: "Vertical lifestyle loop, on-brand color palette, smooth camera orbit, scroll-stopping energy built for social feeds",
    src: "/wino/videos/showreel-5.mp4",
    poster: "/wino/thumbs/video-thumb-5.jpg",
    width: 720,
    height: 1280,
    durationSeconds: 15,
    tags: ["social", "9:16"],
    published: true,
  },
  {
    id: "p6",
    type: "image",
    title: "Neon Market at Midnight",
    description: "A campaign still with the gravity of a film still — neon, night and a world of product placements waiting.",
    category: "ai-image",
    prompt: "Neon-soaked night market, cinematic still, reflections on wet streets, vibrant signage, moody atmospheric depth",
    src: "/wino/images/1.jpeg",
    width: 1536,
    height: 2752,
    tags: ["neon", "night", "still"],
    published: true,
  },
  {
    id: "p7",
    type: "image",
    title: "Face in Studio Light",
    description: "A dramatic studio portrait — the kind of imagery that anchors a campaign identity.",
    category: "ai-image",
    prompt: "Dramatic studio portrait, Rembrandt lighting, confident gaze, editorial campaign quality",
    src: "/wino/images/2.jpeg",
    width: 1536,
    height: 2752,
    tags: ["portrait", "studio", "still"],
    published: true,
  },
  {
    id: "p8",
    type: "image",
    title: "The Long Horizon",
    description: "An expansive cinematic landscape — our stills carry the same scale as our motion.",
    category: "ai-image",
    prompt: "Expansive cinematic landscape, golden hour, layered mountains, epic scale, filmic color grade",
    src: "/wino/images/3.jpeg",
    width: 1536,
    height: 2752,
    tags: ["landscape", "cinematic", "still"],
    published: true,
  },
  {
    id: "p9",
    type: "video",
    title: "First Frames of a Film",
    description: "A narrative teaser with filmic grading and deliberate pacing — a story in 44 seconds.",
    category: "film",
    prompt: "Opening sequence of a mystery film, moody pacing, rain-slicked streets, slow dolly move, suspenseful filmic grade",
    src: "/wino/videos/showreel-6.mp4",
    poster: "/wino/thumbs/video-thumb-6.jpg",
    width: 720,
    height: 1280,
    durationSeconds: 44,
    tags: ["film", "teaser", "9:16"],
    published: true,
  },
  {
    id: "p10",
    type: "video",
    title: "City Pulse 01",
    description: "A vertical slice of street life crafted to hold attention in a scrolling feed.",
    category: "social-media",
    prompt: "Vertical street life, urban rhythm, candid moments, warm daylight, handheld 9:16 energy",
    src: "/wino/videos/vertical-01.mp4",
    poster: "/wino/thumbs/vertical-01.jpg",
    width: 406,
    height: 720,
    durationSeconds: 8,
    tags: ["street", "9:16"],
    published: true,
  },
  {
    id: "p11",
    type: "video",
    title: "City Pulse 02",
    description: "Another street, another mood — consistent energy for brand-led social content.",
    category: "social-media",
    prompt: "Vertical street vignette, cool tones, evening light, natural movement and momentum",
    src: "/wino/videos/vertical-02.mp4",
    poster: "/wino/thumbs/vertical-02.jpg",
    width: 406,
    height: 720,
    durationSeconds: 8,
    tags: ["street", "9:16"],
    published: true,
  },
  {
    id: "p12",
    type: "video",
    title: "City Pulse 03",
    description: "The third beat in a series — proof a campaign can live on repeat without going stale.",
    category: "social-media",
    prompt: "Vertical street series beat, neon accents, night crowd, dynamic 9:16 framing",
    src: "/wino/videos/vertical-03.mp4",
    poster: "/wino/thumbs/vertical-03.jpg",
    width: 406,
    height: 720,
    durationSeconds: 8,
    tags: ["street", "9:16"],
    published: true,
  },
  {
    id: "p13",
    type: "video",
    title: "Portrait in Motion",
    description: "A shallow-depth portrait that moves — cinematic depth for premium brand moments.",
    category: "cinematic",
    prompt: "Cinematic 9:16 portrait, shallow depth of field, gentle camera drift, soft bokeh, premium editorial tone",
    src: "/wino/videos/portrait-moment.mp4",
    poster: "/wino/thumbs/portrait-moment.jpg",
    width: 720,
    height: 1280,
    durationSeconds: 8,
    tags: ["portrait", "bokeh", "9:16"],
    published: true,
  },
  {
    id: "p14",
    type: "video",
    title: "A Film Still, Breathing",
    description: "A composed 16:9 shot with a filmic grade — the quiet power of a locked-off scene.",
    category: "cinematic",
    prompt: "Locked-off 16:9 narrative shot, composed blocking, filmic grade, cinematic stillness",
    src: "/wino/videos/cinematic-01.mp4",
    poster: "/wino/thumbs/cinematic-01.jpg",
    width: 1280,
    height: 720,
    durationSeconds: 8,
    tags: ["16:9", "narrative", "filmic"],
    published: true,
  },
  {
    id: "p15",
    type: "video",
    title: "The Long Take",
    description: "Subtle camera drift across a cinematic frame — motion that never distracts from the story.",
    category: "cinematic",
    prompt: "A single 16:9 take with subtle camera drift, naturalistic light, restrained cinematic motion",
    src: "/wino/videos/cinematic-02.mp4",
    poster: "/wino/thumbs/cinematic-02.jpg",
    width: 1280,
    height: 720,
    durationSeconds: 8,
    tags: ["16:9", "narrative", "filmic"],
    published: true,
  },
  {
    id: "p16",
    type: "video",
    title: "Six Stories, One Frame",
    description: "A wide montage of multiple AI generations — the scale of what one workflow can produce.",
    category: "cinematic",
    prompt: "A wide montage grid of six AI generations, different scenes in one cinematic grade, unified storytelling",
    src: "/wino/videos/showcase-matrix.mp4",
    poster: "/wino/thumbs/showcase-matrix.jpg",
    width: 1280,
    height: 720,
    durationSeconds: 15,
    tags: ["montage", "16:9", "multi-scene"],
    featured: true,
    published: true,
  },
  {
    id: "p17",
    type: "video",
    title: "The Wide Frame",
    description: "An ultrawide text-to-video generation — cinematic scope from a single line of direction.",
    category: "text-to-video",
    prompt: "Ultrawide text-to-video scene, anamorphic scope, epic landscape, cinematic light",
    src: "/wino/videos/seedance-demo.mp4",
    poster: "/wino/thumbs/seedance-demo.jpg",
    width: 1280,
    height: 548,
    durationSeconds: 8,
    tags: ["text-to-video", "wide", "demo"],
    published: true,
  },
  {
    id: "p18",
    type: "video",
    title: "Unbroken",
    description: "A 26-second vertical action sequence — fast cuts, real momentum, zero stunt budget.",
    category: "character",
    prompt: "26-second vertical action sequence, fast cuts, practical energy, stunt-free momentum, 9:16",
    src: "/wino/videos/johnwick-character.mp4",
    poster: "/wino/thumbs/johnwick-character.jpg",
    width: 1080,
    height: 1920,
    durationSeconds: 26,
    tags: ["action", "character", "9:16"],
    featured: true,
    published: true,
  },
  {
    id: "p19",
    type: "video",
    title: "The Workshop Assassin",
    description: "A gritty character vignette in a working workshop — mood, texture and menace on demand.",
    category: "character",
    prompt: "Gritty character vignette in a working workshop, sparks and shadow, cinematic menace, 16:9",
    src: "/wino/videos/factory-ninja.mp4",
    poster: "/wino/thumbs/factory-ninja.jpg",
    width: 1280,
    height: 720,
    durationSeconds: 15,
    tags: ["character", "16:9", "workshop"],
    published: true,
  },
  {
    id: "p20",
    type: "video",
    title: "A Desert Epic",
    description: "An epic-scale trailer sequence from a single prompt — proof that ‘big film’ no longer needs a big budget.",
    category: "film",
    prompt: "Epic sci-fi desert trailer, colossal scale, swirling sand, a lone figure, orchestral tension, 16:9",
    src: "/portfolio/videos/dune-trailer.mp4",
    poster: "/portfolio/thumbs/dune-trailer.jpg",
    width: 1280,
    height: 720,
    durationSeconds: 13,
    tags: ["sci-fi", "trailer", "16:9"],
    featured: true,
    published: true,
  },
  {
    id: "p21",
    type: "video",
    title: "Day One Energy",
    description: "A 30-second fitness vlog with punchy cuts — creator energy, produced to spec.",
    category: "social-media",
    prompt: "30-second fitness vlog, punchy cuts, gym atmosphere, motivational energy, creator style",
    src: "/portfolio/videos/fitness-vlog.mp4",
    poster: "/portfolio/thumbs/fitness-vlog.jpg",
    width: 1280,
    height: 720,
    durationSeconds: 30,
    tags: ["fitness", "vlog", "16:9"],
    published: true,
  },
  {
    id: "p22",
    type: "video",
    title: "Scroll-Stop 01",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical social clip, consistent character and tone, crafted pacing, built to stop the scroll",
    src: "/portfolio/videos/vertical-a1.mp4",
    poster: "/portfolio/thumbs/vertical-a1.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p23",
    type: "video",
    title: "Scroll-Stop 02",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical social clip, consistent character and tone, crafted pacing, built to stop the scroll",
    src: "/portfolio/videos/vertical-a2.mp4",
    poster: "/portfolio/thumbs/vertical-a2.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p24",
    type: "video",
    title: "Scroll-Stop 03",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical social clip, consistent character and tone, crafted pacing, built to stop the scroll",
    src: "/portfolio/videos/vertical-a3.mp4",
    poster: "/portfolio/thumbs/vertical-a3.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p25",
    type: "video",
    title: "Scroll-Stop 04",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical social clip, consistent character and tone, crafted pacing, built to stop the scroll",
    src: "/portfolio/videos/vertical-a4.mp4",
    poster: "/portfolio/thumbs/vertical-a4.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p26",
    type: "video",
    title: "Scroll-Stop 05",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical social clip, consistent character and tone, crafted pacing, built to stop the scroll",
    src: "/portfolio/videos/vertical-a5.mp4",
    poster: "/portfolio/thumbs/vertical-a5.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p27",
    type: "video",
    title: "Scroll-Stop 06",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical social clip, consistent character and tone, crafted pacing, built to stop the scroll",
    src: "/portfolio/videos/vertical-a6.mp4",
    poster: "/portfolio/thumbs/vertical-a6.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p28",
    type: "video",
    title: "Scroll-Stop 07",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical social clip, consistent character and tone, crafted pacing, built to stop the scroll",
    src: "/portfolio/videos/vertical-a7.mp4",
    poster: "/portfolio/thumbs/vertical-a7.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 10,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p29",
    type: "video",
    title: "Scroll-Stop 08",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical social clip, consistent character and tone, crafted pacing, built to stop the scroll",
    src: "/portfolio/videos/vertical-a8.mp4",
    poster: "/portfolio/thumbs/vertical-a8.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p30",
    type: "video",
    title: "Scroll-Stop 09",
    description: "A vertical social clip built to stop the scroll — consistent tone, crafted for the feed.",
    category: "social-media",
    prompt: "Vertical social clip, consistent character and tone, crafted pacing, built to stop the scroll",
    src: "/portfolio/videos/vertical-a9.mp4",
    poster: "/portfolio/thumbs/vertical-a9.jpg",
    width: 640,
    height: 1138,
    durationSeconds: 15,
    tags: ["portrait", "9:16"],
    published: true,
  },
  {
    id: "p31",
    type: "video",
    title: "Cinema Without Cameras",
    description: "A cinematic 16:9 generation from a single prompt — the new economics of filmmaking.",
    category: "cinematic",
    prompt: "Cinematic 16:9 generation from a single prompt, anamorphic look, filmic grade, no camera required",
    src: "/portfolio/videos/web-demo.mp4",
    poster: "/portfolio/thumbs/web-demo.jpg",
    width: 1280,
    height: 720,
    durationSeconds: 13,
    tags: ["16:9", "cinematic"],
    published: true,
  },
];

/** Published samples, featured first, then original order. */
export function loadPortfolioSamples(): PortfolioSample[] {
  return PORTFOLIO_SAMPLES.filter((s) => s.published).sort(
    (a, b) => Number(b.featured ?? false) - Number(a.featured ?? false)
  );
}

export function categoryById(id: string): PortfolioCategory | undefined {
  return PORTFOLIO_CATEGORIES.find((c) => c.id === id);
}

/** "0:08" / "1:02" style clip length. */
export function formatDuration(seconds?: number): string {
  if (!seconds || seconds <= 0) return "";
  const m = Math.floor(seconds / 60);
  const s = Math.round(seconds % 60);
  return `${m}:${String(s).padStart(2, "0")}`;
}

/** Best-effort aspect label like "9:16", "16:9" or "Portrait". */
export function aspectLabel(width: number, height: number): string {
  const ratio = width / height;
  if (Math.abs(ratio - 9 / 16) < 0.02) return "9:16";
  if (Math.abs(ratio - 16 / 9) < 0.02) return "16:9";
  if (Math.abs(ratio - 1) < 0.02) return "1:1";
  return height > width ? "Portrait" : "Landscape";
}